export const VIETNAM_BANKS = [
  "Vietcombank - Ngân hàng TMCP Ngoại thương Việt Nam",
  "VietinBank - Ngân hàng TMCP Công thương Việt Nam",
  "BIDV - Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",
  "Agribank - Ngân hàng Nông nghiệp và Phát triển Nông thôn",
  "Techcombank - Ngân hàng TMCP Kỹ thương Việt Nam",
  "MB Bank - Ngân hàng TMCP Quân đội",
  "ACB - Ngân hàng TMCP Á Châu",
  "VPBank - Ngân hàng TMCP Việt Nam Thịnh Vượng",
  "TPBank - Ngân hàng TMCP Tiên Phong",
  "Sacombank - Ngân hàng TMCP Sài Gòn Thương Tín",
  "HDBank - Ngân hàng TMCP Phát triển TP.HCM",
  "VIB - Ngân hàng TMCP Quốc tế",
  "SHB - Ngân hàng TMCP Sài Gòn - Hà Nội",
  "Eximbank - Ngân hàng TMCP Xuất Nhập khẩu Việt Nam",
  "MSB - Ngân hàng TMCP Hàng Hải",
  "OCB - Ngân hàng TMCP Phương Đông",
  "SCB - Ngân hàng TMCP Sài Gòn",
  "SeABank - Ngân hàng TMCP Đông Nam Á",
  "VietCapital Bank - Ngân hàng TMCP Bản Việt",
  "Bac A Bank - Ngân hàng TMCP Bắc Á",
  "Nam A Bank - Ngân hàng TMCP Nam Á",
  "VietBank - Ngân hàng TMCP Việt Nam Thương Tín",
  "LienViet Post Bank - Ngân hàng TMCP Bưu điện Liên Việt",
  "PVComBank - Ngân hàng TMCP Đại Chúng Việt Nam",
  "Cake by VPBank - Ngân hàng số",
  "Timo by VPBank - Ngân hàng số",
  "Ubank by VPBank - Ngân hàng số",
];
