/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Architectural Blueprint Platform API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery, useMutation } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseMutationOptions,
} from "@tanstack/react-query";

import type {
  GetApiCollaboratorsRequests200,
  GetApiCollaboratorsRequestsParams,
} from "../../api/models";
import type { CollaboratorRequest } from "../../api/types/collaborator";

import { mainInstance } from "../../api/mutator/custom-instance";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Xem danh sách yêu cầu trở thành cộng tác viên (Admin)
 * @summary Xem danh sách yêu cầu trở thành cộng tác viên (Admin)
 */
export const getApiCollaboratorsRequests = (
  params?: GetApiCollaboratorsRequestsParams,
  options?: SecondParameter<typeof mainInstance>,
) => {
  return mainInstance<GetApiCollaboratorsRequests200>(
    { url: `/api/collaborators/requests`, method: "GET", params },
    options,
  );
};

export const getGetApiCollaboratorsRequestsQueryKey = (
  params?: GetApiCollaboratorsRequestsParams,
) => {
  return [`/api/collaborators/requests`, ...(params ? [params] : [])] as const;
};

export const getGetApiCollaboratorsRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCollaboratorsRequests>>,
  TError = unknown,
>(
  params?: GetApiCollaboratorsRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCollaboratorsRequests>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof mainInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiCollaboratorsRequestsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiCollaboratorsRequests>>
  > = ({ signal }) =>
    getApiCollaboratorsRequests(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCollaboratorsRequests>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiCollaboratorsRequestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiCollaboratorsRequests>>
>;
export type GetApiCollaboratorsRequestsQueryError = unknown;

export const useGetApiCollaboratorsRequests = <
  TData = Awaited<ReturnType<typeof getApiCollaboratorsRequests>>,
  TError = unknown,
>(
  params?: GetApiCollaboratorsRequestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCollaboratorsRequests>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof mainInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetApiCollaboratorsRequestsQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Xem thống kê cộng tác viên (Admin)
 * @summary Xem thống kê cộng tác viên (Admin)
 */
export const getApiCollaboratorsStats = (
  options?: SecondParameter<typeof mainInstance>,
) => {
  return mainInstance<GetApiCollaboratorsRequests200>(
    { url: `/api/collaborators/stats`, method: "GET" },
    options,
  );
};

export const getGetApiCollaboratorsStatsQueryKey = () => {
  return [`/api/collaborators/stats`] as const;
};

export const getGetApiCollaboratorsStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCollaboratorsStats>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiCollaboratorsStats>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof mainInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiCollaboratorsStatsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiCollaboratorsStats>>
  > = ({ signal }) => getApiCollaboratorsStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCollaboratorsStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiCollaboratorsStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiCollaboratorsStats>>
>;
export type GetApiCollaboratorsStatsQueryError = unknown;

export const useGetApiCollaboratorsStats = <
  TData = Awaited<ReturnType<typeof getApiCollaboratorsStats>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiCollaboratorsStats>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof mainInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetApiCollaboratorsStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Xem chi tiết yêu cầu cộng tác viên (Admin)
 * @summary Xem chi tiết yêu cầu cộng tác viên (Admin)
 */
export const getApiCollaboratorsRequestsRequestId = (
  requestId: string,
  options?: SecondParameter<typeof mainInstance>,
) => {
  return mainInstance<CollaboratorRequest>(
    { url: `/api/collaborators/requests/${requestId}`, method: "GET" },
    options,
  );
};

export const getGetApiCollaboratorsRequestsRequestIdQueryKey = (
  requestId: string,
) => {
  return [`/api/collaborators/requests/${requestId}`] as const;
};

export const getGetApiCollaboratorsRequestsRequestIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCollaboratorsRequestsRequestId>>,
  TError = unknown,
>(
  requestId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCollaboratorsRequestsRequestId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof mainInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiCollaboratorsRequestsRequestIdQueryKey(requestId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiCollaboratorsRequestsRequestId>>
  > = ({ signal }) =>
    getApiCollaboratorsRequestsRequestId(requestId, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!requestId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCollaboratorsRequestsRequestId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiCollaboratorsRequestsRequestIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiCollaboratorsRequestsRequestId>>
>;
export type GetApiCollaboratorsRequestsRequestIdQueryError = unknown;

export const useGetApiCollaboratorsRequestsRequestId = <
  TData = Awaited<ReturnType<typeof getApiCollaboratorsRequestsRequestId>>,
  TError = unknown,
>(
  requestId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiCollaboratorsRequestsRequestId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof mainInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetApiCollaboratorsRequestsRequestIdQueryOptions(
    requestId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Duyệt yêu cầu trở thành cộng tác viên (Admin)
 * @summary Duyệt yêu cầu trở thành cộng tác viên (Admin)
 */
export const putApiCollaboratorsRequestsRequestIdApprove = (
  requestId: string,
  options?: SecondParameter<typeof mainInstance>,
) => {
  return mainInstance<CollaboratorRequest>(
    { url: `/api/collaborators/requests/${requestId}/approve`, method: "PUT" },
    options,
  );
};

export const usePutApiCollaboratorsRequestsRequestIdApprove = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiCollaboratorsRequestsRequestIdApprove>>,
    TError,
    { requestId: string },
    TContext
  >;
  request?: SecondParameter<typeof mainInstance>;
}) => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn = (props: { requestId: string }) => {
    const { requestId } = props ?? {};

    return putApiCollaboratorsRequestsRequestIdApprove(
      requestId,
      requestOptions,
    );
  };

  return useMutation<
    Awaited<ReturnType<typeof putApiCollaboratorsRequestsRequestIdApprove>>,
    TError,
    { requestId: string },
    TContext
  >({ mutationFn, ...mutationOptions });
};

/**
 * Từ chối yêu cầu trở thành cộng tác viên (Admin)
 * @summary Từ chối yêu cầu trở thành cộng tác viên (Admin)
 */
export const putApiCollaboratorsRequestsRequestIdReject = (
  requestId: string,
  body: { rejectionReason?: string },
  options?: SecondParameter<typeof mainInstance>,
) => {
  return mainInstance<CollaboratorRequest>(
    {
      url: `/api/collaborators/requests/${requestId}/reject`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: body,
    },
    options,
  );
};

export const usePutApiCollaboratorsRequestsRequestIdReject = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiCollaboratorsRequestsRequestIdReject>>,
    TError,
    { requestId: string; data: { rejectionReason?: string } },
    TContext
  >;
  request?: SecondParameter<typeof mainInstance>;
}) => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn = (props: {
    requestId: string;
    data: { rejectionReason?: string };
  }) => {
    const { requestId, data } = props ?? {};

    return putApiCollaboratorsRequestsRequestIdReject(
      requestId,
      data,
      requestOptions,
    );
  };

  return useMutation<
    Awaited<ReturnType<typeof putApiCollaboratorsRequestsRequestIdReject>>,
    TError,
    { requestId: string; data: { rejectionReason?: string } },
    TContext
  >({ mutationFn, ...mutationOptions });
};
