/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Architectural Blueprint Platform API
 * OpenAPI spec version: 1.0.0
 */

export interface UserInfo {
  _id: string;
  username: string;
  email: string;
  role: "user" | "admin" | string;
  createdAt: string;
  updatedAt: string;
}

export interface CollaboratorRequest {
  _id: string;
  user: UserInfo;
  status: "pending" | "approved" | "rejected" | string;
  bankAccount: string;
  bankName: string;
  commissionRate: number;
  approvedBy?: UserInfo;
  approvedAt?: string;
  rejectionReason?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CollaboratorStats {
  _id: string;
  username: string;
  email: string;
  commissionRate: number;
  bankAccount: string;
  bankName: string;
  totalResources: number;
  totalEarnings: number;
}
