/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Architectural Blueprint Platform API
 * OpenAPI spec version: 1.0.0
 */
import type { CollaboratorRequest } from "../types/collaborator";

export interface GetApiCollaboratorsRequestsParams {
  status?: "pending" | "approved" | "rejected";
  page?: number;
  limit?: number;
}

export interface GetApiCollaboratorsRequests200 {
  data?: CollaboratorRequest[];
  pagination?: {
    total?: number;
    page?: number;
    limit?: number;
    totalPages?: number;
  };
}
