/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Architectural Blueprint Platform API
 * OpenAPI spec version: 1.0.0
 */
import type { CollaboratorStats } from "./collaborator";

export interface GetApiCollaboratorsStats200 {
  data?: CollaboratorStats[];
  summary?: {
    totalCollaborators?: number;
    totalResources?: number;
    totalEarnings?: number;
    averageCommission?: number;
  };
}
